### ISSUE TITLE
'GeoAxesSubplot' object has no attribute '_autoscaleXon' issue with cartopy

### ISSUE THREAD

**Issue by stijnvanhoey** [jorisvandenbossche/course-python-geospatial#21]
Notebook 12-xarray-advanced.ipynb returns issue with cartopy: 

```
import cartopy
import cartopy.crs as ccrs

fig = plt.figure(figsize=(9,6))
ax = plt.axes(projection=ccrs.PlateCarree())

ax.add_feature(cartopy.feature.BORDERS, linestyle=':')
era5_mean_temp = era5["t2m"].mean(dim="time") - 273.15
era5_mean_temp.plot.imshow(ax=ax, cmap="coolwarm", 
                           transform=ccrs.PlateCarree(),
                           cbar_kwargs={'shrink': 0.65});
```

See https://github.com/SciTools/cartopy/issues/2086#issuecomment-1256677646, downgrading matplotlib to 3.5.2 fixes the issue.

@jorisvandenbossche  should we pin the matplotlib version for this edition?

**Comment by jorisvandenbossche** [comment]
Yeah, pinning matplotlib to <= 3.5 seems as the best solution for now until cartopy 0.21 can be installed without conflicts

**Comment by stijnvanhoey** [comment]
closing this one, using current version of matplotlib no longer raises issue.
