### ISSUE TITLE
11-xarray-intro: use sentinel tiff file with nodata value defined?

### ISSUE THREAD

**Issue by jorisvandenbossche** [jorisvandenbossche/course-python-geospatial#32]
Currently we have an exercise using "./data/gent/raster/2020-09-17_Sentinel_2_L1C_True_color.tiff" to replace the max nodata value with NaN, but the file itself doesn't actually have that nodata value set in its metadata. If that would be set, we could show that manually replacing NaNs gives the same result as `mask_and_scale=True`.

**Comment by stijnvanhoey** [comment]
```
tc_data = xr.open_dataarray("./data/gent/raster/2020-09-17_Sentinel_2_L1C_True_color.tiff", engine="rasterio", mask_and_scale=False)
tc_data = tc_data.rio.write_nodata(np.array(65535).astype(np.uint16), encoded=True)
tc_data.rio.to_raster("<NEW-FILE>", engine="rasterio")
```
