### ISSUE TITLE
Warnings on dtype conversions and categorical dtype: case-study curieuzeneuze (among others)

### ISSUE THREAD

**Issue by stijnvanhoey** [jorisvandenbossche/course-python-geospatial#37]
Geopandas warning on categorical values:

> /home/stijnvh/.pyenv/versions/miniconda3-latest/envs/DS-geospatial/lib/python3.11/site-packages/geopandas/plotting.py:732: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(values.dtype):

Also for seaborn:

> /home/stijnvh/.pyenv/versions/miniconda3-latest/envs/DS-geospatial/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/home/stijnvh/.pyenv/versions/miniconda3-latest/envs/DS-geospatial/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):
/home/stijnvh/.pyenv/versions/miniconda3-latest/envs/DS-geospatial/lib/python3.11/site-packages/seaborn/_oldcore.py:1498: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(vector):

Also on geopandas
> /home/stijnvh/.pyenv/versions/miniconda3-latest/envs/DS-geospatial/lib/python3.11/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

**Comment by jorisvandenbossche** [comment]
The geopandas one should be fixed with geopandas 0.14 to be released this evening or tomorrow

Seaborn we only use in very few places? (there is no upcoming release)

Other option is to pin pandas to 2.0.x (instead of having 2.1.0), and then that should also avoid those warnings

**Comment by jorisvandenbossche** [comment]
Solved by pinning to pandas 2.0, for the next version of the course we can remove that pin again
